using CounterStrikeSharp.API.Core;

namespace jRandomSkills.src.player;

public interface ISkill
{
    public static void LoadSkill() { }
    public static void EnableSkill(CCSPlayerController player) { }
    public static void DisableSkill(CCSPlayerController player) { }
    public static void UseSkill(CCSPlayerController player) { }
    public static void TypeSkill(CCSPlayerController player, string[] commands) { }
}

public enum Skills
{
    None,
    Aimbot,
    Anomaly,
    AntyFlash,
    AntyHead,
    AreaReaper,
    Armored,
    Assassin,
    Astronaut,
    Baseball,
    Behind,
    BladeMaster,
    BunnyHop,
    C4Camouflage,
    Catapult,
    Chicken,
    ChillOut,
    Cutter,
    Darkness,
    Deactivator,
    Deaf,
    Disarmament,
    Distancer,
    Dracula,
    Duplicator,
    Dwarf,
    EnemySpawn,
    ExplosiveShot,
    FalconEye,
    FastReload,
    Flash,
    Fortnite,
    FragileBomb,
    FriendlyFire,
    FrozenDecoy,
    Ghost,
    Glaz,
    Glitch,
    Glue,
    GodMode,
    HealingSmoke,
    Hermit,
    HolyHandGrenade,
    Impostor,
    InfiniteAmmo,
    Jackal,
    Jammer,
    JumpBan,
    JumpingJack,
    KillerFlash,
    LifeSwap,
    LongKnife,
    LongZeus,
    Medic,
    MoneySwap,
    Muhammed,
    Ninja,
    NoNades,
    NoRecoil,
    Noclip,
    OneShot,
    OnlyHead,
    PawelJumper,
    Phoenix,
    PsychicDefusing,
    Pilot,
    Planter,
    Poison,
    PrimaryBan,
    Prosthesis,
    Push,
    Pyro,
    QuickShot,
    RadarHack,
    Rambo,
    RandomWeapon,
    ReZombie,
    ReactiveArmor,
    Regeneration,
    Replicator,
    Retreat,
    ReturnToSender,
    RichBoy,
    RobinHood,
    Rubber,
    Saper,
    SecondLife,
    Shade,
    ShortBomb,
    Silent,
    SniperElite,
    Soldier,
    SoundMaker,
    Spectator,
    SwapPosition,
    Teleporter,
    Thief,
    ThirdEye,
    ToxicSmoke,
    Wallhack,
    Watchmaker,
    WeaponsSwap,
    Zeus,
}
